名称 = "导航球"
兼容日期 = "2024-11-11"
兼容性标志 = ["nodejs兼容性"]
pages_build_output_dir = ".vercel/output/static"

[env.production.vars]
GITHUB_CLIENT_ID = "Ov23liyiIzokjnsLvy0o"
GITHUB_OWNER = "18419552090"
GITHUB_REPO = "NavSphere"
GITHUB分支 = "主要"
NEXTAUTH_URL = "https://navsphere-cgu.pages.dev/api/auth"
NEXT_PUBLIC_API_URL="https://navsphere-cgu.pages.dev/"

